In [ ]:
# variables
var1 = 78
var2 = (67.89)
var3= "Python"
var4= 'programming'

print(var1)
print(var2)
print(var3)
print(var4)

78
67.89
Python
programming


In [ ]:
print(var1, var2, var3,var4)

78 67.89 Python programming


In [ ]:
base_salary = 10_000_000
print(base_salary)
allowances = 10_000
print(allowances)
tax = 5000

net_salary = base_salary + allowances - tax
print(net_salary)

10000000
10000
10005000


In [ ]:
list1= [10,20,30,40,50,60]

sum1= sum(list1)

print(sum1)

210


In [ ]:
# INDENTATION : means spacing before the command
import numpy as np
v = np.array([10, 20, 30])
m = np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12],
            [13,14,15]
            ]
            ) #2Dlist = rows and columns : 5X3 #MATRIX
print("v:",v, "shape:", v.shape)
print("m:\n", m, "\nshape:", m.shape)
# \n means newline in output
# comments

v: [10 20 30] shape: (3,)
m:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]] 
shape: (5, 3)


In [ ]:
import pandas as pd
df = pd.read_csv("sales-revenue-business-dataset.csv")
print(df)

       index       Date    Year     Month  Customer Age Customer Gender  \
0          0  2/19/2016  2016.0  February          29.0               F   
1          1  2/20/2016  2016.0  February          29.0               F   
2          2  2/27/2016  2016.0  February          29.0               F   
3          3  3/12/2016  2016.0     March          29.0               F   
4          4  3/12/2016  2016.0     March          29.0               F   
...      ...        ...     ...       ...           ...             ...   
34862  34862   2/7/2016  2016.0  February          38.0               M   
34863  34863  3/13/2015  2015.0     March          38.0               M   
34864  34864   4/5/2015  2015.0     April          38.0               M   
34865  34865  8/30/2015  2015.0    August          38.0               M   
34866  34866        NaN     NaN       NaN           NaN             NaN   

             Country           State Product Category     Sub Category  \
0      United States     

In [ ]:
# DATA PRE-PROCESSING
df = df.drop('column1' , axis=1)

In [ ]:
df.columns

Index(['index', 'Date', 'Year', 'Month', 'Customer Age', 'Customer Gender',
       'Country', 'State', 'Product Category', 'Sub Category', 'Quantity',
       'Unit Cost', 'Unit Price', 'Cost', 'Revenue', 'Column1'],
      dtype='object')

In [ ]:
df.isnull()

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34862,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
34863,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
34864,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
34865,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True


In [ ]:
# missing the filling values
# filling means replace the NaN values with 0
df.fillna(0)

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1
0,0,2/19/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.000000,0.0
1,1,2/20/2016,2016.0,February,29.0,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.000000,0.0
2,2,2/27/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.000000,0.0
3,3,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.000000,0.0
4,4,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34862,34862,2/7/2016,2016.0,February,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,2.0,1160.00,985.500000,2320.0,1971.000000,0.0
34863,34863,3/13/2015,2015.0,March,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2049.00,1583.000000,2049.0,1583.000000,0.0
34864,34864,4/5/2015,2015.0,April,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,3.0,683.00,560.666667,2049.0,1682.000000,0.0
34865,34865,8/30/2015,2015.0,August,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2320.00,1568.000000,2320.0,1568.000000,0.0


In [ ]:
# dropna (will remove the entire row with NaN value)
df = df.dropna()

In [ ]:
df

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1
312,312,1/11/2016,2016.0,January,40.0,M,France,Yveline,Bikes,Road Bikes,3.0,567.00,790.0,1701.0,2370.0,2370.000000
313,313,1/11/2016,2016.0,January,40.0,M,France,Yveline,Accessories,Helmets,2.0,192.50,199.0,385.0,398.0,398.000000
314,314,1/18/2016,2016.0,January,40.0,M,France,Yveline,Bikes,Mountain Bikes,2.0,1160.00,1511.5,2320.0,3023.0,3023.000000
315,315,1/18/2016,2016.0,January,40.0,M,France,Yveline,Accessories,Bottles and Cages,2.0,115.00,147.0,230.0,294.0,294.000000
316,316,1/18/2016,2016.0,January,40.0,M,France,Yveline,Accessories,Bottles and Cages,1.0,140.00,167.0,140.0,167.0,167.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2881,2881,1/5/2016,2016.0,January,28.0,M,United Kingdom,England,Accessories,Fenders,2.0,176.00,229.0,352.0,458.0,1971.000000
2882,2882,1/7/2016,2016.0,January,28.0,M,United Kingdom,England,Accessories,Fenders,1.0,506.00,590.0,506.0,590.0,1583.000000
2883,2883,2/20/2016,2016.0,February,28.0,M,United Kingdom,England,Accessories,Fenders,3.0,117.33,159.0,352.0,477.0,1682.000000
2884,2884,2/24/2016,2016.0,February,28.0,M,United Kingdom,England,Accessories,Fenders,1.0,286.00,390.0,286.0,390.0,1568.000000


In [ ]:
df.to_csv("cleaned_sales_dataset.csv")

In [ ]:
# feature engineering
df = df.drop("unnamed: 0", axis = 1)

In [ ]:
df.columns

Index(['index', 'Date', 'Year', 'Month', 'Customer Age', 'Customer Gender',
       'Country', 'State', 'Product Category', 'Sub Category', 'Quantity',
       'Unit Cost', 'Unit Price', 'Cost', 'Revenue', 'Column1'],
      dtype='object')

In [ ]:
# create a new column
df['profit] = df['revenue']-df['cost']

In [ ]:
df.head()
# .head() shows top 5 rows
# .tail() shows bottom 5 rows

In [ ]:
# create profit margin column
df['profit_margin'] = df['profit']/df['revenue']

In [ ]:
df.head()

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1
312,312,1/11/2016,2016.0,January,40.0,M,France,Yveline,Bikes,Road Bikes,3.0,567.0,790.0,1701.0,2370.0,2370.0
313,313,1/11/2016,2016.0,January,40.0,M,France,Yveline,Accessories,Helmets,2.0,192.5,199.0,385.0,398.0,398.0
314,314,1/18/2016,2016.0,January,40.0,M,France,Yveline,Bikes,Mountain Bikes,2.0,1160.0,1511.5,2320.0,3023.0,3023.0
315,315,1/18/2016,2016.0,January,40.0,M,France,Yveline,Accessories,Bottles and Cages,2.0,115.0,147.0,230.0,294.0,294.0
316,316,1/18/2016,2016.0,January,40.0,M,France,Yveline,Accessories,Bottles and Cages,1.0,140.0,167.0,140.0,167.0,167.0


KeyError: 'country'